// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkaBV7aeZrsgTyUIeMs1EmmyJA5SiLKAY',
    appId: '1:381473826253:web:7073b7ffdbada1e77d9084',
    messagingSenderId: '381473826253',
    projectId: 'gestion-esmia',
    authDomain: 'gestion-esmia.firebaseapp.com',
    storageBucket: 'gestion-esmia.firebasestorage.app',
    measurementId: 'G-PQ027JQS4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMO3uOBpFYfLaFVxSans0rYr9S1GlGLn8',
    appId: '1:381473826253:android:e44153b3eab8a1857d9084',
    messagingSenderId: '381473826253',
    projectId: 'gestion-esmia',
    storageBucket: 'gestion-esmia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6C7y6HU2k-CkFK0Kvivhq6Kv86J2ogsw',
    appId: '1:381473826253:ios:25946542189995b97d9084',
    messagingSenderId: '381473826253',
    projectId: 'gestion-esmia',
    storageBucket: 'gestion-esmia.firebasestorage.app',
    iosClientId: '381473826253-19uoh7co4doj545fem6ddgv50qbh8e3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fivondronana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6C7y6HU2k-CkFK0Kvivhq6Kv86J2ogsw',
    appId: '1:381473826253:ios:25946542189995b97d9084',
    messagingSenderId: '381473826253',
    projectId: 'gestion-esmia',
    storageBucket: 'gestion-esmia.firebasestorage.app',
    iosClientId: '381473826253-19uoh7co4doj545fem6ddgv50qbh8e3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fivondronana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkaBV7aeZrsgTyUIeMs1EmmyJA5SiLKAY',
    appId: '1:381473826253:web:c83680bec191fd877d9084',
    messagingSenderId: '381473826253',
    projectId: 'gestion-esmia',
    authDomain: 'gestion-esmia.firebaseapp.com',
    storageBucket: 'gestion-esmia.firebasestorage.app',
    measurementId: 'G-GMF0S5HK78',
  );

}